export default {
  api: {
    news: {
      url: `${process.env.NEWS_API_URL}/news/all`,
      token: process.env.NEWS_API_TOKEN,
    },
    options: {
      url: `${process.env.OPTION_CHAIN_API_URL}/options`,
    },
    orders: {
      url: `${process.env.OPTION_CHAIN_API_URL}/orders`,
    },
    symbols: {
      url: `${process.env.OPTION_CHAIN_API_URL}/symbols`,
    },
  },
  symbols: [
    'tsla',
    'dkng',
    'spy',
    'meta',
    'amzn',
    'aapl',
    'googl',
    'nvda',
    'iwm',
    'epd',
    'qqq',
    'amc',
    'cmg',
    'amd',
    'intc',
    'gs',
    'uber',
    'dis',
    'hood',
    'lyft',
    'mdb',
    'lcid',
    'gme',
    'wmt',
    'abnb',
    'roku',
    'shop',
    'coin',
    'cvna',
    'adbe',
    'amgn',
    'sq',
    'hd',
    'kvue',
    'tgt',
    'pypl',
    'mrna',
    'se',
    'slv',
    'snap',
    'msft',
    'sofi',
    'baba',
    'pbr',
  ],
};
